version: "2.1"

services:

  api:
    build: ./src/server
    container_name: "api"
    image: "api"
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - "3001:3001"      