version: "2.1"

services:

  api:
    build: ./src/server
    container_name: "api"
    image: "api"
    restart: always
    environment:
      - NODE_ENV=local
    ports:
      - "3001:3001"    
    links:
      - db      
    depends_on:
      db:
        condition: service_healthy
      
  db:
    image: "mongo:3.6.2"
    container_name: "db"
    restart: always
    volumes:
      - ./data/db:/data/db  
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.stats().ok'
      interval: 15s
      timeout: 10s
      retries: 5
