version: "2.1"

services:
  
  web:
    build: ./src/web
    container_name: "web"
    restart: always
    ports:
      - "80:80"

  server:
    build: ./src/server
    container_name: "server"
    restart: always
    ports:
      - "3001:3001"      
    links:
      - db      
    depends_on:
      db:
        condition: service_healthy

  db:
    image: "mongo:3.6.2"
    container_name: "db"
    restart: always
    volumes:
      - ./data/db:/data/db  
    healthcheck:
      test: echo 'db.stats().ok'
      interval: 15s
      timeout: 10s
      retries: 5